# Generated by Django 4.1.4 on 2022-12-14 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_category_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_image',
            new_name='image',
        ),
    ]
